### PR TITLE
[17.0][MIG] sign_oca: Migration to 17.0

### PR DESCRIPTION
**Pull request by peluko00**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please include #22

**Comment by victoralmau** [comment]
Please, include https://github.com/OCA/sign/pull/28 + https://github.com/OCA/sign/pull/39

**Comment by peluko00** [comment]
> Please, include #28 + #39

Done, thanks!

**Comment by victoralmau** [comment]
Please, include https://github.com/OCA/sign/pull/42

Sorry, I want to review this PR today or tomorrow

**Review by victoralmau — CHANGES_REQUESTED** [review]
Code review seems to be correct but I have not been able to test it functionally (when I go to runboat and try to log in it gives an error because it seems it is not adapted to owl correctly).

**Comment by peluko00** [comment]
> Please, include #42
> 
> Sorry, I want to review this PR today or tomorrow

Done, thanks!

**Comment by peluko00** [comment]
> Code review seems to be correct but I have not been able to test it functionally (when I go to runboat and try to log in it gives an error because it seems it is not adapted to owl correctly).

Not really yet, i need to revise how to replace the registerModel function in v17. Any idea?

**Comment by victoralmau** [comment]
> Not really yet, i need to revise how to replace the registerModel function in v17. Any idea?

Sorry, I don't know exactly what the right way would be in this case, although there are probably examples in core modules that can help you.

**Comment by victoralmau** [comment]
Please, include https://github.com/OCA/sign/pull/41 + https://github.com/OCA/sign/pull/45

**Comment by victoralmau** [comment]
Please, include https://github.com/OCA/sign/pull/63

**Comment by victoralmau** [comment]
Before reviewing it I see that you have included the changes in the migration commit instead of cherry-picking the corresponding commits and adding it **before** the v17 migration commit. Can you change it?

**Comment by flotho** [comment]
Tried to install on a local database and have this issue : 
image

nothing special in the server logs.
In the browser I have : 
```
Caused by: TypeError: Comp1 is undefined
    slot2@http://localhost:8069/web/assets/500d77e/web.assets_web.min.js line 1503 > Function:21:72
    callSlot@http://localhost:8069/web/assets/500d77e/web.assets_web.min.js:1109:25
    template@http://localhost:8069/web/assets/500d77e/web.assets_web.min.js line 1503 > Function:8:12
    _render@http://localhost:8069/web/assets/500d77e/web.assets_web.min.js:940:96
    render@http://localhost:8069/web/assets/500d77e/web.assets_web.min.js:939:6
    initiateRender@http://localhost:8069/web/assets/500d77e/web.assets_web.min.js:1007:47
    async*createComponent/<@http://localhost:8069/web/assets/500d77e/web.assets_web.min.js:1543:80
    template@http://localhost:8069/web/assets/500d77e/web.assets_web.min.js line 1503 > Function:58:24
    _render@http://localhost:8069/web/assets/500d77e/web.assets_web.min.js:940:96
    render@http://localhost:8069/web/assets/500d77e/web.assets_web.min.js:939:6
    initiateRender@http://localhost:8069/web/assets/500d77e/web.assets_web.min.js:1007:47
    async*createComponent/<@http://localhost:8069/web/assets/500d77e/web.assets_web.min.js:1543:80
    template@http://localhost:8069/web/assets/500d77e/web.assets_web.min.js line 1503 > Function:12:12
    _render@http://localhost:8069/web/assets/500d77e/web.assets_web.min.js:940:96
    render@http://localhost:8069/web/assets/500d77e/web.assets_web.min.js:939:6
    initiateRender@http://localhost:8069/web/assets/500d77e/web.assets_web.min.js:1007:47
    async*mountComponent@http://localhost:8069/web/assets/500d77e/web.assets_web.min.js:1003:120
    mountNode@http://localhost:8069/web/assets/500d77e/web.assets_web.min.js:1529:20
    mount@http://localhost:8069/web/assets/500d77e/web.assets_web.min.js:1525:64
    mountComponent@http://localhost:8069/web/assets/500d77e/web.assets_web.min.js:1582:207
    async*startWebClient@http://localhost:8069/web/assets/500d77e/web.assets_web.min.js:18781:740
    async*@http://localhost:8069/web/assets/500d77e/web.assets_web.min.js:18778:226
    startModule@http://localhost:8069/web/assets/500d77e/web.assets_web.min.js:11:159
    startModules@http://localhost:8069/web/assets/500d77e/web.assets_web.min.js:10:57
    addJob@http://localhost:8069/web/assets/500d77e/web.assets_web.min.js:7:39
    define@http://localhost:8069/web/assets/500d77e/web.assets_web.min.js:6:141
    @http://localhost:8069/web/assets/500d77e/web.assets_web.min.js:18781:6
```

impossible to find this Comp1 in the base code.

**Comment by victoralmau** [comment]
Please, include https://github.com/OCA/sign/pull/69

**Comment by victoralmau** [comment]
Superseded by https://github.com/OCA/sign/pull/70

**Pull request closed without merging**
