### PR TITLE
[14.0][ADD] maintenance_sign_oca: New module

### PR DESCRIPTION
**Pull request by victoralmau**
Superseed: https://github.com/OCA/sign/pull/2

New module

Changes done:
- [x] Add smart-buttons to equipments.
- [x] Add maintenance configuration to set a sign template to auto-create the requests.
- [x] Create requests automatically when a owner is assigned.

Locked by:
- [x] sign_oca: https://github.com/OCA/sign/pull/8

@Tecnativa TT41745

### CODE REVIEW

**Comment by victoralmau** [comment]
Finally this is ready to review. Ping @pedrobaeza and @carolinafernandez-tecnativa

**Comment by carolinafernandez-tecnativa** [comment]
When access with admin and only with Sign group User only see my own documents to menu Sign, i got this error message:

image

**Comment by victoralmau** [comment]
Thanks, solved.

**Comment by carolinafernandez-tecnativa** [comment]
Hi,

1- What do you think on adding a button to Sign only one equipment?

image

Because if I want to only sign for one equipment i must go to tree view in order to select only one.

2- If the user has Sign-User: Own Documents Only, is not being able to select sign template:

image

Is it okay?

Thanks!

**Comment by victoralmau** [comment]
I have added a new approach at https://github.com/OCA/sign/pull/20 that would reduce the code of this module.

**Comment by victoralmau** [comment]
It is now ready for review.

**Comment by marcelsavegnago** [comment]
ping @WesleyOliveira98

**Review by WesleyOliveira98 — APPROVED** [review]
[FUNCTIONAL REVIEW]

Manual Sign Request Creation
image

image

image

image

The smart button on equipment linked to  Sign Requests
image

Automatic Sign Request Creation
image

image

image

LGTM!

**Review by carolinafernandez-tecnativa — APPROVED** [review]
LGTM Thanks!

**Review by marcelsavegnago — APPROVED** [review]

**Pull request merged**
