### PR TITLE
[14.0][FIX] sign_oca: Duplicated Sign button in request

### PR DESCRIPTION
**Pull request by PauBForgeFlow**
Unify to_sign and signer_is_allow_signature fields which had the same purpose

### CODE REVIEW

**Comment by etobella** [comment]
Seems legit, can you send a picture of before and after?

**Comment by PauBForgeFlow** [comment]
Before:

image

After:

image

**Review by etobella — APPROVED** [review]
@victoralmau Can I kindly ask for your review? :pray:

**Review by victoralmau — APPROVED** [review]
Functional review OK

**Pull request merged**
