### PR TITLE
[16.0][FIX]: translation in owl templates

### PR DESCRIPTION
**Pull request by Demacri**
Load it.po terms in owl frontend templates too

### CODE REVIEW

**Comment by pedrobaeza** [comment]
If I don't remember bad, what you should do is:

```python
from odoo import models
class IrHttp(models.AbstractModel):
    _inherit = "ir.http"

    @classmethod
    def _get_translation_frontend_modules_name(cls):
        mods = super(IrHttp, cls)._get_translation_frontend_modules_name()
        return mods + ["sign_oca"]
```

**Comment by pedrobaeza** [comment]
You must also follow commit message guidelines: https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#commit-message

**Comment by Demacri** [comment]
> If I don't remember bad, what you should do is:
> 
> ```python
> from odoo import models
> class IrHttp(models.AbstractModel):
>     _inherit = "ir.http"
> 
>     @classmethod
>     def _get_translation_frontend_modules_name(cls):
>         mods = super(IrHttp, cls)._get_translation_frontend_modules_name()
>         return mods + ["sign_oca"]
> ```

From what i understand, this avoid to call "session.load_translations" (is it right?), but I'm not able to find a useful documentation about how to handle this scenario in owl components. 

PS: fixed commit guidelines, sorry for the inconvenience.

**Comment by etobella** [comment]
According to Pedro, the change he is asking says:

Return a list of module name where web-translations and
            dynamic resources may be used in frontend views

Actually, some Odoo modules  use it, like payment, portal or im_livechat

**Pull request closed without merging**
