### PR TITLE
[17.0][MIG] maintenance_sign_oca: Migration to 17.0

### PR DESCRIPTION
**Pull request by victoralmau**
Migration to 17.0

Please @pilarvargas-tecnativa and @CarlosRoca13 can you review it?

@Tecnativa TT51852

### CODE REVIEW

**Comment by victoralmau** [comment]
Ping @pilarvargas-tecnativa @CarlosRoca13

**Review by CarlosRoca13 — APPROVED** [review]
:+1: Code review

**Review by pilarvargas-tecnativa — APPROVED** [review]

**Pull request merged**
