### PR TITLE
[16.0][IMP] sign_oca: Use flex in order to show it properly

### LINKED ISSUE #43: [16.0][BUG] PDF Viewer Header Overlap Issue
## Module
sign_oca

## Describe the bug
When scrolling to the bottom of the PDF document, the header overlaps with the content, causing the bottom part of the document to be cut off and obscured from view.

This is proved by the scrollbar which goes out of the screen
image

When I remove the header from the inspector I can see the entire document correctly
image
image

## To Reproduce
**Affected versions**:
16.0 (don't check on other versions)

1. Open a pdf to sign
2. Try to scroll to the very bottom of the document

**Expected behavior**
The entire content of the PDF should be visible, including the bottom part, without any part being obscured by the header.

**Additional context**)
Odoo version: 16.0-20240417

### PR DESCRIPTION
**Pull request by etobella**
Fixes #43 
The same happened with the configuration

### CODE REVIEW

**Comment by etobella** [comment]
@TheClaud99 can you check in runboat?

**Comment by etobella** [comment]
It affects 14 and 15 too. Once it is merged I will back port it

**Comment by hitrosol** [comment]
I can't see the runboat link :)

**Comment by etobella** [comment]
> I can't see the runboat link :)

@hitrosol You can check it now :smile:

**Comment by pedrobaeza** [comment]
Do you have screenshot of the before/after?

**Comment by etobella** [comment]
Before:

image

After:

image


You can see the end of the frame on the after

**Review by pedrobaeza — APPROVED** [review]

**Review by hitrosol — APPROVED** [review]
I can access the runboat now, but when I try to sign the doc, the response of the signature box is very slow. It's faster when I tried in my local, and it successfully signed and validated.

**Pull request merged**
