### PR TITLE
[17.0][MIG] sign_oca: Migration to 17.0

### PR DESCRIPTION
**Pull request by victoralmau**
Supersedes https://github.com/OCA/sign/pull/33

Migration to 17.0

@Tecnativa TT51500

### CODE REVIEW

**Review by lauradiaz22 — COMMENTED** [review]
Good morning,
During the functional review, I have detected an error:
When I enter inside the signature module, and click on configure of a template already created, it sends me the following error with traceability:
 
TypeError: Dialog.alert is not a function
    at SignOcaConfigure.waitIframeLoaded (http://oca-sign-17-0-pr70-75d32b584ed1.runboat.odoo-community.org/web/assets/4024fef/web.assets_web.min.js:15167:193)
    at http://oca-sign-17-0-pr70-75d32b584ed1.runboat.odoo-community.org/web/assets/4024fef/web.assets_web.min.js:15168:289

And once the error closes, a message appears informing you that the pdf file is corrupt or invalid.

**Review by sheragar — COMMENTED** [review]
During the functional testing, I have detected the following error.
When accessing one of the "sign requests," the "signed" button displays the following error: 
KeyNotFoundError: Cannot find sign_oca_preview in this registry!
    Error: Cannot find sign_oca_preview in this registry!
        at Registry.get (http://oca-sign-17-0-pr70-75d32b584ed1.runboat.odoo-community.org/web/assets/4024fef/web.assets_web.min.js:3384:76)
        at _executeClientAction (http://oca-sign-17-0-pr70-75d32b584ed1.runboat.odoo-community.org/web/assets/4024fef/web.assets_web.min.js:10283:87)
        at doAction (http://oca-sign-17-0-pr70-75d32b584ed1.runboat.odoo-community.org/web/assets/4024fef/web.assets_web.min.js:10299:192)
        at async Object.doActionButton (http://oca-sign-17-0-pr70-75d32b584ed1.runboat.odoo-community.org/web/assets/4024fef/web.assets_web.min.js:10306:196)
        at async execute (http://oca-sign-17-0-pr70-75d32b584ed1.runboat.odoo-community.org/web/assets/4024fef/web.assets_web.min.js:9930:293)
        at async executeButtonCallback (http://oca-sign-17-0-pr70-75d32b584ed1.runboat.odoo-community.org/web/assets/4024fef/web.assets_web.min.js:9923:34)

Additionally, when selecting the "Activity log" button, another error appears:
EvalError: Can not evaluate python expression: ([("request_id", "=", id)])
    Error: Name 'id' is not defined
    EvalError: Can not evaluate python expression: ([("request_id", "=", id)])
    Error: Name 'id' is not defined
        at evaluateExpr (http://oca-sign-17-0-pr70-75d32b584ed1.runboat.odoo-community.org/web/assets/4024fef/web.assets_web.min.js:3058:54)
        at _preprocessAction (http://oca-sign-17-0-pr70-75d32b584ed1.runboat.odoo-community.org/web/assets/4024fef/web.assets_web.min.js:10216:150)
        at doAction (http://oca-sign-17-0-pr70-75d32b584ed1.runboat.odoo-community.org/web/assets/4024fef/web.assets_web.min.js:10298:170)
        at async Object.doActionButton (http://oca-sign-17-0-pr70-75d32b584ed1.runboat.odoo-community.org/web/assets/4024fef/web.assets_web.min.js:10306:196)
        at async execute (http://oca-sign-17-0-pr70-75d32b584ed1.runboat.odoo-community.org/web/assets/4024fef/web.assets_web.min.js:9930:293)
        at async executeButtonCallback (http://oca-sign-17-0-pr70-75d32b584ed1.runboat.odoo-community.org/web/assets/4024fef/web.assets_web.min.js:9923:34)

**Comment by victoralmau** [comment]
Thank you for your comments, the PR is still in draft because we are finishing to solve the errors, it will be ready soon.

**Comment by CarlosRoca13** [comment]
I think that all problems are solved right now

**Review by CarlosRoca13 — APPROVED** [review]

**Review by victoralmau — COMMENTED** [review]
Functional review OK

**Review by lauradiaz22 — APPROVED** [review]
Functional review and this LGTM 👍

**Pull request merged**
