### PR TITLE
[15.0][MIG] sign_oca: Migration to 15.0

### PR DESCRIPTION
**Pull request by victoralmau**
Migration to 15.0

Please @pedrobaeza can you review it?

@Tecnativa TT41745

### CODE REVIEW

**Comment by victoralmau** [comment]
@etobella can you review it?

**Comment by etobella** [comment]
Right click on edition is not working. Can you review?

**Comment by victoralmau** [comment]
> Right click on edition is not working. Can you review?

Fixed, thanks!

**Comment by etobella** [comment]
Signature works, but I cannot configure properly, as the elements cannot be moved or increased

**Comment by victoralmau** [comment]
> Signature works, but I cannot configure properly, as the elements cannot be moved or increased

Oops, I have checked about it but I can't find the reason, can you check it?

**Comment by pedrobaeza** [comment]
#27 should be added here. Can you please reactivate this?

**Comment by victoralmau** [comment]
Right-click on edition is fixed. It is ready for review, thank you!

**Comment by PauBForgeFlow** [comment]
When a sign request is created from some other model through 'Sign from template' action, this request does not have signers associated. Is this the normal behavior?

image

**Comment by PauBForgeFlow** [comment]
When a sign request is created directly from the 'Create' button in sign request, only not required fields are allowed to sign.

image

Request configure page:
image

Sign request page:
image

**Comment by victoralmau** [comment]
> When a sign request is created directly from the 'Create' button in sign request, only not required fields are allowed to sign.
> 
> image
> 
> Request configure page: image
> 
> Sign request page: image

Reviewing what you indicate in runboat, I have been able to complete all the fields.

sign_oca-configure
sign_oca-request
sign_oca-fin

By any chance does the same thing also happen to you in v14 or v16?

**Comment by victoralmau** [comment]
> When a sign request is created from some other model through 'Sign from template' action, this request does not have signers associated. Is this the normal behavior?
> 

I have removed the action in relation to `sign.oca*` models but it is still shown in the rest of the sites (`res.partner` for example). 

Yes, it is correct that the requests that are created do not have `signer_ids`, you can review [maintenance_sign_oca](https://github.com/OCA/sign/tree/14.0/maintenance_sign_oca) (v14) to better understand its implementation. Actually there is confusion and mix between signer_ids and what is configured in templates (fields) but that is something conceptual that has its advantages and disadvantages.

**Comment by pedrobaeza** [comment]
Maybe some clarification in the README?

**Comment by PauBForgeFlow** [comment]
> > When a sign request is created directly from the 'Create' button in sign request, only not required fields are allowed to sign.
> > image
> > Request configure page: image
> > Sign request page: image
> 
> Reviewing what you indicate in runboat, I have been able to complete all the fields.
> 
> sign_oca-configure sign_oca-request sign_oca-fin
> 
> By any chance does the same thing also happen to you in v14 or v16?

I don't know what the difference is in our steps, but I just tested it in runboat and the problem persists for me.

In addition, I detected that an Error arises when I want to delete a field in the configuration of the same process.

**Comment by victoralmau** [comment]
Changes done:
- [x] Improve readme.
- [x] Avoid the error if a field is deleted in the configuration process (the same error also occurs in v14 and v16).

@PauBForgeFlow Can you try to reproduce the error in v14 or v16 or make a mini-video so I can check it?

**Comment by PauBForgeFlow** [comment]
> Changes done:
> 
> * [x]  Improve readme.
> * [x]  Avoid the error if a field is deleted in the configuration process (the same error also occurs in v14 and v16).
> 
> @PauBForgeFlow Can you try to reproduce the error in v14 or v16 or make a mini-video so I can check it?

In v14 the error also occurs, so surly in v16 too. Maybe it is better to make a fix in the v14 also with fixing the error when a field is deleted and FW the FIX commit, WDYT? I attach you a mini-video of the process.

[Screencast from 19-04-24 10:09:15.webm](https://github.com/OCA/sign/assets/137763287/7ef8ecce-d26e-410d-9a93-c41de30f6ef5)

**Comment by victoralmau** [comment]
I have created a PR to 14.0 with the misc fixes that have been done here (when merged I will add it to the commit history before the migration commit).

The use case you indicate in the video (also happens in v14) I see it only happens in **runboat**, so I don't know why (you can look into it if you want).

**Comment by victoralmau** [comment]
It is ready for review.

**Review by pedrobaeza — APPROVED** [review]
When you click no "Validate & send document", no message is put and the button doesn't disappear, so the user gets confused if it has been sent or not. This is not something exclusive for this migration I think.

**Review by PauBForgeFlow — APPROVED** [review]
LGTM!

**Comment by victoralmau** [comment]
> When you click no "Validate & send document", no message is put and the button doesn't disappear, so the user gets confused if it has been sent or not. This is not something exclusive for this migration I think.

Exactly, this is something already detected in https://github.com/OCA/sign/issues/23 that will have to be improve (in another PR) to avoid confusion.

**Pull request merged**
