### PR TITLE
[14.0][ADD] project_task_sign_oca: add new module

### PR DESCRIPTION
**Pull request by WesleyOliveira98**
This pull request replaces #48. The original pull request was closed due to an accidental branch deletion.

This module allows you to generate manual and automatic signature requests from project tasks to task customers.

Create and view sign requests directly from project tasks
image

Define a template to enable automatic sign requests process
image

The sign request will be linked to the project and task, and the customer (`partner_id`) of the task as a signer with the role defined in template.
image

cc: @victoralmau @marcelsavegnago @kaynnan @Matthwhy @douglascstd

### CODE REVIEW

**Review by victoralmau — APPROVED** [review]
Code and functional review OK.

**Review by marcelsavegnago — APPROVED** [review]

**Comment by marcelsavegnago** [comment]
ping @etobella

**Review by kaynnan — APPROVED** [review]
LGTM

**Review by etobella — APPROVED** [review]
/ocabot merge nobump

**Pull request merged**
