### PR TITLE
[16.0][MIG] sign_oca: Migration to 16.0

### PR DESCRIPTION
**Pull request by etobella**
Adapted to OWL

### CODE REVIEW

**Comment by pedrobaeza** [comment]
/ocabot migration sign_oca

What about 15.0?

**Comment by BernatPForgeFlow** [comment]
Functional test looks good!

**Review by BernatPForgeFlow — APPROVED** [review]

**Comment by AlexPForgeFlow** [comment]
Functional test looks good!

**Comment by AlexPForgeFlow** [comment]
LGTM!

**Review by AlexPForgeFlow — APPROVED** [review]

**Comment by etobella** [comment]
/ocabot merge nobump

About 15.0, I will probably Backport this one when I have some free time :wink: Otherwise, any help is welcome

**Pull request merged**
